[package]
name = "gtnh-recipe-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
clap = { version = "4.5.9", features = ["derive"] }
itertools = "0.13.0"
strsim = "0.11.1"
